services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - goapp-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  goapp:
    container_name: goapp-auth
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - goapp-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PW}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

networks:
  goapp-network:
    driver: bridge
